name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ibtida01
          password: devopsIUT

      - name: Build Docker image
        run: |
          docker build -t ibtida01/dockerimg:latest .
          docker push ibtida01/dockerimg:latest

      - name: Set up Kubernetes
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: 
          resource-group: 

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/
